//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Token
    {
        public int token_id { get; set; }
        public string token_text { get; set; }
        public int usid { get; set; }
        public System.DateTime token_time { get; set; }
        public bool IsDel { get; set; }
    
        public virtual UserInfo UserInfo { get; set; }
    }
}
